version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo "Installing dependencies..."
      - pip install requests -t lib
      - pip install requests_aws4auth -t lib
  build:
    commands:
      - echo "Zipping deployment package..."
      - cd lib
      - zip -r9 ../deployment_package.zip .
      - cd ..
      - mv deployment_package.zip deployment_package_index_photos.zip
      - cp deployment_package_index_photos.zip deployment_package_search_photos.zip
      - mv index-photos.py lambda_function.py
      - zip -g deployment_package_index_photos.zip lambda_function.py
      - mv search-photos.py lambda_function.py
      - zip -g deployment_package_search_photos.zip lambda_function.py
      - mv searchbot-hook.py lambda_function.py
      - zip ./deployment_package_searchbot_hoot.zip lambda_function.py
  post_build:
    commands:
      - echo "Updating lambda Function..."
      - aws lambda update-function-code --function-name index-photos --zip-file fileb://deployment_package_index_photos.zip
      - aws lambda update-function-code --function-name search-photos --zip-file fileb://deployment_package_search_photos.zip
      - aws lambda update-function-code --function-name searchbot-hook --zip-file fileb://deployment_package_searchbot_hoot.zip
      - echo "DONE!!"